# Generated by Django 4.1.5 on 2023-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitorCount",
            fields=[
                (
                    "visit_date",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("visit_count", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
