# Generated by Django 4.1.7 on 2023-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField()),
                ('sub_text_1', models.TextField(blank=True, null=True)),
                ('sub_text_2', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='images/banner')),
            ],
        ),
    ]
