# Generated by Django 4.1.5 on 2023-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="endDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="startDate",
            field=models.DateField(),
        ),
    ]
