# Generated by Django 4.1.5 on 2023-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_alter_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="noticeImg",
            field=models.ImageField(blank=True, null=True, upload_to="images/notice"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
