# Generated by Django 4.1.5 on 2023-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=300)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("time", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "shopImg",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/restaurant"
                    ),
                ),
            ],
            options={
                "db_table": "restaurants",
            },
        ),
    ]
