# Generated by Django 4.1.5 on 2023-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
