# Generated by Django 4.1.5 on 2023-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_restaurantmenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="shopType",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
