# Generated by Django 4.1.5 on 2023-02-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_restaurant_shoptype"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="restaurantmenu",
            table="restaurantMenu",
        ),
    ]
