# Generated by Django 4.1.7 on 2023-04-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurantmenu_restaurant_alter_restaurant_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmenu',
            old_name='restaurant',
            new_name='shop',
        ),
    ]
