# Generated by Django 4.1.5 on 2023-01-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bar",
            old_name="barImg",
            new_name="shopImg",
        ),
    ]
