# Generated by Django 4.1.5 on 2023-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0002_rename_barimg_bar_shopimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
