# Generated by Django 4.1.5 on 2023-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0003_bar_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
