# Generated by Django 4.1.5 on 2023-02-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0004_barmenu"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="barmenu",
            table="barMenu",
        ),
    ]
