# Generated by Django 4.1.7 on 2023-03-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_alter_barmenu_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmenu',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.bar'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
