# Generated by Django 4.1.7 on 2023-04-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_barmenu_bar_alter_bar_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barmenu',
            old_name='bar',
            new_name='shop',
        ),
    ]
