# Generated by Django 4.1.5 on 2023-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("contact", models.CharField(max_length=50)),
                ("number", models.CharField(blank=True, max_length=100, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "clubImg",
                    models.ImageField(blank=True, null=True, upload_to="images/club"),
                ),
            ],
            options={
                "db_table": "clubs",
            },
        ),
    ]
