# Generated by Django 4.1.5 on 2023-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cafe",
            name="time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
