# Generated by Django 4.1.5 on 2023-01-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_cafe_phone_alter_cafe_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafe",
            old_name="cafeImg",
            new_name="shopImg",
        ),
    ]
