# Generated by Django 4.1.5 on 2023-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0003_rename_cafeimg_cafe_shopimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
