# Generated by Django 4.1.7 on 2023-03-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_cafemenu_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafemenu',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
