# Generated by Django 4.1.7 on 2023-04-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_cafemenu_cafe_alter_cafe_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafemenu',
            old_name='cafe',
            new_name='shop',
        ),
    ]
